# Generated by Django 4.2 on 2023-04-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_remove_currencytype_user_alter_user_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payapp.currencytype'),
        ),
    ]
