# Generated by Django 4.2 on 2023-04-27 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_alter_user_currency_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencytype',
            name='currency_amount',
        ),
    ]
